pipeline {
  agent { dockerfile
    {
      dir 'docker'
    }

  }

  stages{
    stage('Build'){
      steps{
        sh 'node --version'
        echo "Get working directory"
        sh  'pwd'
      }
    }
  }
}
